### ISSUE TITLE
isnt working

### ISSUE THREAD

**Issue by Sandorka77** [cralin/repository.cralin.Kodi_19.repodata#1]
hello Cralin
Sorry to disturb you but i have the latest kodi ( 19.3 ) i have vpn but when i installed the files says isnt working .. why .. or just in romanian network can use ?
i really wanted to use with kodi
Thx

**Comment by cralin** [comment]
Hi,
This is a techical repository and no bugs/issues will be solved if opened against the contents of this repo.
